### PR TITLE
Added errors and submitErrors to FormState

### LINKED ISSUE #5: Feature: Supply errors object to form subscribers
See: https://github.com/erikras/react-final-form/issues/3#issuecomment-347644175

### PR DESCRIPTION
**Pull request by erikras**
Closes #5.

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
@erikras Don't forget to delete the branch 😉🙂

**Comment by erikras** [comment]
@MichaelDeBoey Calm down, son. Old dusty branches never hurt anyone! 😆

**Comment by MichaelDeBoey** [comment]
@erikras Just a kind reminder thats all 🙂

**Comment by erikras** [comment]
Published in [`v1.1.0`](https://github.com/erikras/final-form/releases/tag/v1.1.0).

**Pull request merged**
