### PR TITLE
Use $Shape<T> instead of optional fields

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Ref: https://github.com/facebook/flow/pull/5251/files#diff-453a8ac419736c97694ea5b93d1965e0R120

### CODE REVIEW

**Comment by erikras** [comment]
Fascinating! I had no idea that was an option. That's pretty bleeding edge to reference a docs PR! 😎 

Thanks!

**Comment by MichaelDeBoey** [comment]
@erikras There's no script to run `prettier`, or did I overlooked it? 😕

**Comment by erikras** [comment]
It's _supposed_ to run on `precommit`, but sometimes it doesn't. The setup looks identical on `react-final-form`, and it works on one and not on the other... 🤷‍♂️

**Comment by MichaelDeBoey** [comment]
@erikras `$Shape` already exists in `flow`, but just isn't documented yet... 😕
@aikar's PR (facebook/flow#5251) just adds a good explanation, so was a good reference for this PR 🙂

**Comment by erikras** [comment]
Published in [`v1.1.0`](https://github.com/erikras/final-form/releases/tag/v1.1.0).

**Pull request merged**
